[package]
name = "denispionicul/cooldown"
version = "1.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Create debounces with ease."

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.0.0"
WaitFor = "sleitnick/wait-for@0.2.2"